import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("C:/Users/namiy/Downloads/Housing.csv")
print(df.columns)
print(df.isnull().sum())
plt.figure()
plt.scatter(df['area'], df['price'])
plt.xlabel("Area")
plt.ylabel("Price")
plt.title("Area vs Price")
plt.show()
corr = df.corr()
plt.figure()
plt.imshow(corr)
plt.colorbar()
plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
plt.yticks(range(len(corr.columns)), corr.columns)
plt.title("Correlation Heatmap")
plt.show()
